const translations = {
    en: {
        gameTitle: "Egyptian Rat Screw",
        play: "Play",
        playBots: "Start With Bots",
        playMulti: "Multiplayer Start",
        settings: "Settings",
        theme: "Theme",
        themeClassic: "Classic Table",
        themeGreen: "Green Table",
        themeBlue: "Blue Table",
        themeRed: "Red Table",
        themeDark: "Dark Table",
        difficulty: "Difficulty",
        diffEasy: "Easy",
        diffMedium: "Medium",
        diffHard: "Hard",
        language: "Language",
        back: "Back",
        quit: "Quit",
        you: "YOU",
        tapToPlay: "TAP TO PLAY",
        tapToSlap: "TAP TO SLAP",
        slapMsg: "SLAPPED!",
        wonMsg: "WON PILE",
        burnMsg: "BURNED CARD",
        challengeMsg: "CHALLENGE!",
        chances: "CHANCES",
        winMsg: "WINS!",
        played: "played",
        wonThePile: "won the pile!",
        burnedACard: "burned a card",
        enterName: "Enter your name:",
        rules: "Game Rules",
        objectiveTitle: "Objective",
        objectiveText: "Collect all cards to win the game.",
        gameplayTitle: "Gameplay",
        gameplayText: "Players take turns placing cards on the center pile.",
        challengeTitle: "Challenge System",
        challengeText: "Face cards start a challenge and the next player must defend.",
        slapRulesTitle: "Slap Rules",
        slapRulesGeneral: "Players can slap the pile when special patterns appear.",
        slapDoubles: "Doubles:",
        slapDoublesDesc: "Two identical cards in a row.",
        slapTens: "Tens:",
        slapTensDesc: "Two number cards adding up to 10.",
        slapMarriage: "Marriage:",
        slapMarriageDesc: "King and Queen next to each other.",
        slapSandwich: "Sandwich:",
        slapSandwichDesc: "Two identical cards with one card between them.",
        win: "Congratulations!",
        defeat: "DEFEAT!",
        playAgain: "Play Again",
        returnMenu: "Main Menu",
        youWonMsg: "You won the game!",
        botWonMsg: "won the game!",
        music: "Music & Ambience",
        sfx: "Sound Effects",
        scoreLabel: "Score",
        usernameLabel: "Username",
        topPlayers: "Top Players",
        account: "Account",
        phPlayer: "Player",
        phUsername: "Username",
        phEmail: "Email",
        phPassword: "Password",
        signIn: "Sign In",
        needAccount: "Need an account? Register",
        register: "Register",
        backToLogin: "Back to Login",
        signOut: "Sign Out",
        close: "Close",
        loading: "Loading...",
        noPlayers: "No players found.",
        failedLoad: "Failed to load scoreboard.",
        welcome: "Welcome",
        multiplayerLobby: "Multiplayer Lobby",
        createTable: "Create Table",
        or: "OR",
        phTableId: "Enter Table ID",
        joinTable: "Join Table",
        waitingRoom: "Waiting Room",
        tableId: "Table ID",
        copyId: "Copy ID",
        players: "Players",
        waitingPlayer: "Waiting...",
        startGame: "Start Game",
        leaveTable: "Leave Table",
        copied: "Copied!",
        invalidTableId: "Invalid Table ID",
        tableNotFound: "Table not found or full",
        loginRequired: "Please log in to play multiplayer.",
        hostLeft: "Host closed the table."
    },
    tr: {
        gameTitle: "Mısır Faresi",
        play: "Oyna",
        playBots: "Botlarla Oyna",
        playMulti: "Çok Oyunculu",
        settings: "Ayarlar",
        theme: "Tema",
        themeClassic: "Klasik Masa",
        themeGreen: "Yeşil Masa",
        themeBlue: "Mavi Masa",
        themeRed: "Kırmızı Masa",
        themeDark: "Koyu Masa",
        difficulty: "Zorluk",
        diffEasy: "Kolay",
        diffMedium: "Normal",
        diffHard: "Zor",
        language: "Dil",
        back: "Geri",
        quit: "Çıkış",
        you: "SEN",
        tapToPlay: "KART AT",
        tapToSlap: "ŞAP!",
        slapMsg: "ŞAPLADI!",
        wonMsg: "DESTEYİ ALDI",
        burnMsg: "KART YAKTI",
        challengeMsg: "MEYDAN OKUMA!",
        chances: "HAK",
        winMsg: "KAZANDI!",
        played: "oynadı:",
        wonThePile: "desteyi aldı!",
        burnedACard: "kart yaktı",
        enterName: "Adınızı Giriniz:",
        rules: "Oyun Kuralları",
        objectiveTitle: "Hedef",
        objectiveText: "Oyunu kazanmak için tüm kartları toplayın.",
        gameplayTitle: "Oynanış",
        gameplayText: "Oyuncular sırayla ortaya kart atarlar.",
        challengeTitle: "Meydan Okuma",
        challengeText: "Resimli kartlar meydan okuma başlatır, sıradaki savunmalıdır.",
        slapRulesTitle: "Şap Kuralları",
        slapRulesGeneral: "Özel desenler belirdiğinde desteye şaplayabilirsiniz.",
        slapDoubles: "Çiftler:",
        slapDoublesDesc: "Art arda iki aynı kart.",
        slapTens: "Onlular:",
        slapTensDesc: "Toplamı 10 eden iki sayı kartı.",
        slapMarriage: "Evlilik:",
        slapMarriageDesc: "Yan yana Papaz ve Kız.",
        slapSandwich: "Sandviç:",
        slapSandwichDesc: "Arasında bir kart olan iki aynı kart.",
        win: "Tebrikler!",
        defeat: "Yenilgi!",
        playAgain: "Tekrar Oyna",
        returnMenu: "Ana Menü",
        youWonMsg: "Oyunu kazandın!",
        botWonMsg: "oyunu kazandı!",
        music: "Müzik ve Ortam Sesi",
        sfx: "Ses Efektleri",
        scoreLabel: "Skor",
        usernameLabel: "Kullanıcı Adı",
        topPlayers: "En İyiler",
        account: "Hesap",
        phPlayer: "Oyuncu",
        phUsername: "Kullanıcı Adı",
        phEmail: "E-posta",
        phPassword: "Şifre",
        signIn: "Giriş Yap",
        needAccount: "Hesabın yok mu? Kayıt Ol",
        register: "Kayıt Ol",
        backToLogin: "Girişe Dön",
        signOut: "Çıkış Yap",
        close: "Kapat",
        loading: "Yükleniyor...",
        noPlayers: "Oyuncu bulunamadı.",
        failedLoad: "Skor tablosu yüklenemedi.",
        welcome: "Hoş Geldin",
        multiplayerLobby: "Çok Oyunculu Lobi",
        createTable: "Masa Kur",
        or: "VEYA",
        phTableId: "Masa ID Girin",
        joinTable: "Masaya Katıl",
        waitingRoom: "Bekleme Odası",
        tableId: "Masa ID",
        copyId: "ID Kopyala",
        players: "Oyuncular",
        waitingPlayer: "Bekleniyor...",
        startGame: "Oyunu Başlat",
        leaveTable: "Masadan Ayrıl",
        copied: "Kopyalandı!",
        invalidTableId: "Geçersiz Masa ID",
        tableNotFound: "Masa bulunamadı veya dolu",
        loginRequired: "Çok oyunculu oynamak için giriş yapın.",
        hostLeft: "Kurucu masayı kapattı."
    },
    de: {
        gameTitle: "Ägyptisches Rattenschrauben",
        play: "Spielen",
        playBots: "Mit Bots starten",
        playMulti: "Mehrspieler-Start",
        settings: "Einstellungen",
        theme: "Thema",
        themeClassic: "Klassischer Tisch",
        themeGreen: "Grüner Tisch",
        themeBlue: "Blauer Tisch",
        themeRed: "Roter Tisch",
        themeDark: "Dunkler Tisch",
        difficulty: "Schwierigkeit",
        diffEasy: "Leicht",
        diffMedium: "Mittel",
        diffHard: "Schwer",
        language: "Sprache",
        back: "Zurück",
        quit: "Beenden",
        you: "DU",
        tapToPlay: "SPIELEN",
        tapToSlap: "KLATSCHEN!",
        slapMsg: "GEKLATSCHT!",
        wonMsg: "STAPEL GEWONNEN",
        burnMsg: "KARTE VERBRANNT",
        challengeMsg: "HERAUSFORDERUNG!",
        chances: "CHANCEN",
        winMsg: "GEWINNT!",
        played: "spielte:",
        wonThePile: "hat den Stapel gewonnen!",
        burnedACard: "hat eine Karte verbrannt",
        enterName: "Gib deinen Namen ein:",
        rules: "Spielregeln",
        objectiveTitle: "Ziel",
        objectiveText: "Sammle alle Karten, um das Spiel zu gewinnen.",
        gameplayTitle: "Spielablauf",
        gameplayText: "Die Spieler legen abwechselnd Karten auf den mittleren Stapel.",
        challengeTitle: "Herausforderungssystem",
        challengeText: "Bildkarten starten eine Herausforderung und der nächste Spieler muss verteidigen.",
        slapRulesTitle: "Klatsch-Regeln",
        slapRulesGeneral: "Spieler können auf den Stapel klatschen, wenn spezielle Muster erscheinen.",
        slapDoubles: "Doppel:",
        slapDoublesDesc: "Zwei identische Karten hintereinander.",
        slapTens: "Zehner:",
        slapTensDesc: "Zwei Zahlenkarten, die zusammen 10 ergeben.",
        slapMarriage: "Ehe:",
        slapMarriageDesc: "König und Königin nebeneinander.",
        slapSandwich: "Sandwich:",
        slapSandwichDesc: "Zwei identische Karten mit einer Karte dazwischen.",
        win: "Glückwunsch!",
        defeat: "NIEDERLAGE!",
        playAgain: "Nochmal spielen",
        returnMenu: "Hauptmenü",
        youWonMsg: "Du hast das Spiel gewonnen!",
        botWonMsg: "gewann das Spiel!",
        music: "Musik & Ambiente",
        sfx: "Soundeffekte",
        scoreLabel: "Punkte",
        usernameLabel: "Benutzername",
        topPlayers: "Top-Spieler",
        account: "Konto",
        phPlayer: "Spieler",
        phUsername: "Benutzername",
        phEmail: "E-Mail",
        phPassword: "Passwort",
        signIn: "Anmelden",
        needAccount: "Kein Konto? Registrieren",
        register: "Registrieren",
        backToLogin: "Zurück zur Anmeldung",
        signOut: "Abmelden",
        close: "Schließen",
        loading: "Wird geladen...",
        noPlayers: "Keine Spieler gefunden.",
        failedLoad: "Fehler beim Laden der Anzeigetafel.",
        welcome: "Willkommen",
        multiplayerLobby: "Mehrspieler-Lobby",
        createTable: "Tisch erstellen",
        or: "ODER",
        phTableId: "Tisch-ID eingeben",
        joinTable: "Tisch beitreten",
        waitingRoom: "Warteraum",
        tableId: "Tisch-ID",
        copyId: "ID kopieren",
        players: "Spieler",
        waitingPlayer: "Warten...",
        startGame: "Spiel starten",
        leaveTable: "Tisch verlassen",
        copied: "Kopiert!",
        invalidTableId: "Ungültige Tisch-ID",
        tableNotFound: "Tisch nicht gefunden oder voll",
        loginRequired: "Bitte melde dich an, um zu spielen.",
        hostLeft: "Gastgeber hat den Tisch geschlossen."
    },
    ru: {
        gameTitle: "Египетский крысиный винт",
        play: "Играть",
        playBots: "Игра с ботами",
        playMulti: "Мультиплеер",
        settings: "Настройки",
        theme: "Тема",
        themeClassic: "Классический Стол",
        themeGreen: "Зеленый Стол",
        themeBlue: "Синий Стол",
        themeRed: "Красный стол",
        themeDark: "Темный стол",
        difficulty: "Сложность",
        diffEasy: "Легко",
        diffMedium: "Средне",
        diffHard: "Сложно",
        language: "Язык",
        back: "Назад",
        quit: "Выход",
        you: "ВЫ",
        tapToPlay: "ХОДИТЬ",
        tapToSlap: "ХЛОПАТЬ!",
        slapMsg: "ХЛОПНУЛ!",
        wonMsg: "ВЗЯЛ СТОПКУ",
        burnMsg: "СЖЕГ КАРТУ",
        challengeMsg: "ВЫЗОВ!",
        chances: "ШАНСЫ",
        winMsg: "ПОБЕДА!",
        played: "сыграл:",
        wonThePile: "забрал стопку!",
        burnedACard: "сжег карту",
        enterName: "Введите ваше имя:",
        rules: "Правила игры",
        objectiveTitle: "Цель",
        objectiveText: "Соберите все карты, чтобы выиграть игру.",
        gameplayTitle: "Игровой процесс",
        gameplayText: "Игроки по очереди кладут карты в центральную стопку.",
        challengeTitle: "Система вызовов",
        challengeText: "Карты-картинки начинают вызов, следующий игрок должен защищаться.",
        slapRulesTitle: "Правила хлопков",
        slapRulesGeneral: "Игроки могут бить по стопке, когда появляются особые комбинации.",
        slapDoubles: "Двойни:",
        slapDoublesDesc: "Две одинаковые карты подряд.",
        slapTens: "Десятки:",
        slapTensDesc: "Две числовые карты, в сумме дающие 10.",
        slapMarriage: "Брак:",
        slapMarriageDesc: "Король и дама рядом.",
        slapSandwich: "Сэндвич:",
        slapSandwichDesc: "Две одинаковые карты с одной картой между ними.",
        win: "Поздравляем!",
        defeat: "ПОРАЖЕНИЕ!",
        playAgain: "Играть снова",
        returnMenu: "Главное меню",
        youWonMsg: "Вы выиграли игру!",
        botWonMsg: "выиграл игру!",
        music: "Музыка и Фон",
        sfx: "Звуковые Эффекты",
        scoreLabel: "Счет",
        usernameLabel: "Имя пользователя",
        topPlayers: "Лучшие игроки",
        account: "Аккаунт",
        phPlayer: "Игрок",
        phUsername: "Имя пользователя",
        phEmail: "Эл. почта",
        phPassword: "Пароль",
        signIn: "Войти",
        needAccount: "Нет аккаунта? Регистрация",
        register: "Регистрация",
        backToLogin: "Вернуться ко входу",
        signOut: "Выйти",
        close: "Закрыть",
        loading: "Загрузка...",
        noPlayers: "Игроки не найдены.",
        failedLoad: "Не удалось загрузить таблицу.",
        welcome: "Добро пожаловать",
        multiplayerLobby: "Многопользовательское лобби",
        createTable: "Создать стол",
        or: "ИЛИ",
        phTableId: "Введите ID стола",
        joinTable: "Присоединиться к столу",
        waitingRoom: "Комната ожидания",
        tableId: "ID Стола",
        copyId: "Копир. ID",
        players: "Игроки",
        waitingPlayer: "Ожидание...",
        startGame: "Начать игру",
        leaveTable: "Покинуть стол",
        copied: "Скопировано!",
        invalidTableId: "Неверный ID стола",
        tableNotFound: "Стол не найден или заполнен",
        loginRequired: "Пожалуйста, войдите для игры.",
        hostLeft: "Хост закрыл стол."
    }
};

let currentLang = 'en';

export const Localization = {
    init(lang) {
        currentLang = translations[lang] ? lang : 'en';
        this.apply();
    },

    setLanguage(lang) {
        if (translations[lang]) {
            currentLang = lang;
            this.apply();
            return true;
        }
        return false;
    },

    get(key) {
        return translations[currentLang][key] || key;
    },

    apply() {
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (translations[currentLang][key]) {
                if (el.tagName === 'INPUT' && el.type !== 'checkbox' && el.type !== 'radio') {
                    el.placeholder = translations[currentLang][key];
                } else {
                    el.innerText = translations[currentLang][key];
                }
            }
        });

        // Allow modules to react to language change
        import('./eventbus.js').then(module => {
            module.default.emit('languageChanged', currentLang);
        });
    }
};
